"""empty message

Revision ID: 7d94f34cef72
Revises: e716a1f24b61
Create Date: 2019-08-30 02:27:59.681967

"""

# revision identifiers, used by Alembic.
revision = '7d94f34cef72'
down_revision = 'e716a1f24b61'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('webhooks', sa.Column('host', sa.VARCHAR(length=100), nullable=False))
    op.add_column('webhooks', sa.Column('method', sa.VARCHAR(length=64), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('webhooks', 'method')
    op.drop_column('webhooks', 'host')
    # ### end Alembic commands ###
