"""empty message

Revision ID: bae5d7fd7d95
Revises: ee92df5db310
Create Date: 2019-08-30 02:01:36.400313

"""

# revision identifiers, used by Alembic.
revision = 'bae5d7fd7d95'
down_revision = 'ee92df5db310'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Webhooks',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('event', sa.VARCHAR(length=64), nullable=False),
    sa.Column('endpoint', sa.VARCHAR(length=64), nullable=False),
    sa.Column('extra_paylod', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Webhooks')
    # ### end Alembic commands ###
