"""empty message

Revision ID: e716a1f24b61
Revises: 0f13e6d8b6c6
Create Date: 2019-08-30 02:15:59.874255

"""

# revision identifiers, used by Alembic.
revision = 'e716a1f24b61'
down_revision = '0f13e6d8b6c6'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('webhooks', 'extra_paylod',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('webhooks', 'extra_paylod',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    # ### end Alembic commands ###
