"""empty message

Revision ID: ee92df5db310
Revises: None
Create Date: 2019-08-26 02:42:59.760271

"""

# revision identifiers, used by Alembic.
revision = 'ee92df5db310'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', name='statusenum'), nullable=False),
    sa.Column('created_by', sa.VARCHAR(length=64), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.VARCHAR(length=64), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.Column('sku', sa.VARCHAR(length=64), nullable=False),
    sa.Column('name', sa.VARCHAR(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('sku')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('products')
    # ### end Alembic commands ###
